FROM php:7.2-cli as testbase

RUN apt-get update
RUN apt-get install -y curl software-properties-common git unzip gnupg2 mysql-server
RUN curl -sL https://deb.nodesource.com/setup_10.x | bash -
RUN apt-get install -y nodejs
RUN curl -sS https://getcomposer.org/installer -o composer-setup.php
RUN php composer-setup.php --install-dir=/usr/local/bin --filename=composer

CMD ['sh']