FROM php:7 as build
RUN apt-get update -y && apt-get install -y libmcrypt-dev openssl git
RUN pecl install mcrypt-1.0.2
RUN docker-php-ext-enable mcrypt
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
RUN docker-php-ext-install pdo_mysql
WORKDIR /app
COPY ./ /app
RUN echo "<?php" > routes/api.php && echo "<?php" > routes/web.php;
RUN composer install
