FROM php:7 as build
RUN apt-get update -y && apt-get install -y libmcrypt-dev openssl git unzip libzip-dev
RUN pecl install mcrypt-1.0.2
RUN docker-php-ext-enable mcrypt && docker-php-ext-install pdo_mysql zip
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer